// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.vardb.resources;

import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;
import org.vardb.resources.Family;

privileged aspect FamilyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FamilyDataOnDemand: @Component;
    
    private Random FamilyDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Family> FamilyDataOnDemand.data;
    
    public Family FamilyDataOnDemand.getNewTransientFamily(int index) {
        org.vardb.resources.Family obj = new org.vardb.resources.Family();
        obj.setIdentifier("identifier_" + index);
        obj.setName("name_" + index);
        obj.setDescription("description_" + index);
        return obj;
    }
    
    public Family FamilyDataOnDemand.getSpecificFamily(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Family obj = data.get(index);
        return Family.findFamily(obj.getId());
    }
    
    public Family FamilyDataOnDemand.getRandomFamily() {
        init();
        Family obj = data.get(rnd.nextInt(data.size()));
        return Family.findFamily(obj.getId());
    }
    
    public boolean FamilyDataOnDemand.modifyFamily(Family obj) {
        return false;
    }
    
    public void FamilyDataOnDemand.init() {
        data = org.vardb.resources.Family.findFamilyEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Family' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.vardb.resources.Family>();
        for (int i = 0; i < 10; i++) {
            org.vardb.resources.Family obj = getNewTransientFamily(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
