// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.vardb.resources;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.vardb.resources.FamilyDataOnDemand;

privileged aspect FamilyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FamilyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FamilyIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FamilyIntegrationTest: @Transactional;
    
    @Autowired
    private FamilyDataOnDemand FamilyIntegrationTest.dod;
    
    @Test
    public void FamilyIntegrationTest.testCountFamilys() {
        org.junit.Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", dod.getRandomFamily());
        long count = org.vardb.resources.Family.countFamilys();
        org.junit.Assert.assertTrue("Counter for 'Family' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FamilyIntegrationTest.testFindFamily() {
        org.vardb.resources.Family obj = dod.getRandomFamily();
        org.junit.Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Family' failed to provide an identifier", id);
        obj = org.vardb.resources.Family.findFamily(id);
        org.junit.Assert.assertNotNull("Find method for 'Family' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Family' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FamilyIntegrationTest.testFindAllFamilys() {
        org.junit.Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", dod.getRandomFamily());
        long count = org.vardb.resources.Family.countFamilys();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Family', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.vardb.resources.Family> result = org.vardb.resources.Family.findAllFamilys();
        org.junit.Assert.assertNotNull("Find all method for 'Family' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Family' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FamilyIntegrationTest.testFindFamilyEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", dod.getRandomFamily());
        long count = org.vardb.resources.Family.countFamilys();
        if (count > 20) count = 20;
        java.util.List<org.vardb.resources.Family> result = org.vardb.resources.Family.findFamilyEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Family' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Family' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FamilyIntegrationTest.testFlush() {
        org.vardb.resources.Family obj = dod.getRandomFamily();
        org.junit.Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Family' failed to provide an identifier", id);
        obj = org.vardb.resources.Family.findFamily(id);
        org.junit.Assert.assertNotNull("Find method for 'Family' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFamily(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Family' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FamilyIntegrationTest.testMerge() {
        org.vardb.resources.Family obj = dod.getRandomFamily();
        org.junit.Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Family' failed to provide an identifier", id);
        obj = org.vardb.resources.Family.findFamily(id);
        boolean modified =  dod.modifyFamily(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.vardb.resources.Family merged = (org.vardb.resources.Family) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Family' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FamilyIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", dod.getRandomFamily());
        org.vardb.resources.Family obj = dod.getNewTransientFamily(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Family' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Family' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Family' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FamilyIntegrationTest.testRemove() {
        org.vardb.resources.Family obj = dod.getRandomFamily();
        org.junit.Assert.assertNotNull("Data on demand for 'Family' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Family' failed to provide an identifier", id);
        obj = org.vardb.resources.Family.findFamily(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Family' with identifier '" + id + "'", org.vardb.resources.Family.findFamily(id));
    }
    
}
