// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.vardb.resources;

import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;
import org.vardb.resources.Pathogen;

privileged aspect PathogenDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PathogenDataOnDemand: @Component;
    
    private Random PathogenDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Pathogen> PathogenDataOnDemand.data;
    
    public Pathogen PathogenDataOnDemand.getNewTransientPathogen(int index) {
        org.vardb.resources.Pathogen obj = new org.vardb.resources.Pathogen();
        obj.setIdentifier("identifier_" + index);
        obj.setName("name_" + index);
        obj.setDescription("description_" + index);
        return obj;
    }
    
    public Pathogen PathogenDataOnDemand.getSpecificPathogen(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Pathogen obj = data.get(index);
        return Pathogen.findPathogen(obj.getId());
    }
    
    public Pathogen PathogenDataOnDemand.getRandomPathogen() {
        init();
        Pathogen obj = data.get(rnd.nextInt(data.size()));
        return Pathogen.findPathogen(obj.getId());
    }
    
    public boolean PathogenDataOnDemand.modifyPathogen(Pathogen obj) {
        return false;
    }
    
    public void PathogenDataOnDemand.init() {
        data = org.vardb.resources.Pathogen.findPathogenEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Pathogen' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.vardb.resources.Pathogen>();
        for (int i = 0; i < 10; i++) {
            org.vardb.resources.Pathogen obj = getNewTransientPathogen(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
