// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.vardb.sequences;

import java.lang.String;

privileged aspect Sequence_Roo_ToString {
    
    public String Sequence.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Identifier: ").append(getIdentifier()).append(", ");
        sb.append("Accession: ").append(getAccession()).append(", ");
        sb.append("Sequence: ").append(getSequence()).append(", ");
        sb.append("Disease: ").append(getDisease()).append(", ");
        sb.append("Pathogen: ").append(getPathogen()).append(", ");
        sb.append("Family: ").append(getFamily());
        return sb.toString();
    }
    
}
