// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.vardb.sequences;

import java.lang.String;
import org.vardb.resources.Disease;
import org.vardb.resources.Family;
import org.vardb.resources.Pathogen;

privileged aspect Sequence_Roo_JavaBean {
    
    public String Sequence.getIdentifier() {
        return this.identifier;
    }
    
    public void Sequence.setIdentifier(String identifier) {
        this.identifier = identifier;
    }
    
    public String Sequence.getAccession() {
        return this.accession;
    }
    
    public void Sequence.setAccession(String accession) {
        this.accession = accession;
    }
    
    public String Sequence.getSequence() {
        return this.sequence;
    }
    
    public void Sequence.setSequence(String sequence) {
        this.sequence = sequence;
    }
    
    public Disease Sequence.getDisease() {
        return this.disease;
    }
    
    public void Sequence.setDisease(Disease disease) {
        this.disease = disease;
    }
    
    public Pathogen Sequence.getPathogen() {
        return this.pathogen;
    }
    
    public void Sequence.setPathogen(Pathogen pathogen) {
        this.pathogen = pathogen;
    }
    
    public Family Sequence.getFamily() {
        return this.family;
    }
    
    public void Sequence.setFamily(Family family) {
        this.family = family;
    }
    
}
